export const TEMPLATE_DATA = {
  fullName: "",
  hours: "",
  address: "",
  phone: "",
  latitude: 0,
  longitude: 0,
  domainName: "",
  contactEmail: "",
  reservationLink: "",
  takeoutLink: "",
  noveltyLink: "",
  mainLogo: "",
  navLogo: "",
  heroImg: "",
  heroVideo: "",
  heroVideoPoster: "",
  menuRoute: "",
  header: {
    ctaList: [{ cta: "", ctaLink: "", ctaDownload: false }],
    logoUrl: "",
  },
  content: [
    {
      title: "",
      content: "",
      contentImg: "",
      ctaList: [{ cta: "", ctaLink: "", ctaDownload: false }],
    },
  ],
};
